{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "external-service-discovery-operator.fullname" . }}-manager
  labels: {{- include "external-service-discovery-operator.labels" . | nindent 4 }}
rules:
{{ .Files.Get "generated/manager-role-rules.yaml" | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "external-service-discovery-operator.fullname" . }}-manager
  labels: {{- include "external-service-discovery-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "external-service-discovery-operator.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "external-service-discovery-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
