apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-service-discovery-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "external-service-discovery-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels: {{- include "external-service-discovery-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}{{- toYaml . | nindent 8 }}{{- end }}
      labels:
        {{- include "external-service-discovery-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}{{- toYaml . | nindent 8 }}{{- end }}
    spec:
      serviceAccountName: {{ include "external-service-discovery-operator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [/manager]
          args:
            - --health-probe-bind-address=:8081
            - {{ printf "--discovery-refresh-interval=%s" .Values.discovery.refreshInterval | quote }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - {name: healthz, containerPort: 8081, protocol: TCP}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            httpGet: {path: /healthz, port: healthz}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet: {path: /readyz, port: healthz}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts: [{name: tmp, mountPath: /tmp}]
      volumes: [{name: tmp, emptyDir: {}}]
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
